version: '3.4'

services:

  data.service:
    container_name: dataapi
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "SensorDatabaseSettings:ConnectionString=mongodb://mongo:27017"
    ports:
      - "5001:80"
  
  device.service:
    container_name: deviceapi
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5002:80"

  analytics.service:
    container_name: analyticsapi
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "SensorDatabaseSettings:ConnectionString=mongodb://mongo:27017"
    ports:
      - "5003:80"

  command.service:
    container_name: commandapi
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5004:80"

  aktuator.service:
    container_name: aktuatorapi
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5005:80"

  apigateway:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - data.service
      - device.service
      - command.service
      - analytics.service
      - aktuator.service
    ports:
      - "8000:80"