version: '3.4'

services:

  mongo:
    image: mongo
    restart: always
    volumes:
      - ${WEBAPP_STORAGE_HOME}/site:/data/db
    ports:
      - 27017:27017

  rabbitmq:
    container_name: rabbitmq
    ports:
     - 5672:5672
     - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password        
    image: rabbitmq:3-management

  data.service:
    restart: always
    image: ${DOCKER_REGISTRY-}dataapi
    build:
      context: .
      dockerfile: Services/Data/DataService/Dockerfile
    depends_on:
      - rabbitmq
      - mongo

  device.service:
    image: ${DOCKER_REGISTRY-}deviceapi
    build:
      context: .
      dockerfile: Services/Device/Device/Dockerfile
    depends_on:
      - rabbitmq

  analytics.service:
    restart: always
    image: ${DOCKER_REGISTRY-}analyticsapi
    build:
      context: .
      dockerfile: Services/Analytics/Analytics/Dockerfile
    depends_on:
      - rabbitmq
      - mongo


  command.service:
    image: ${DOCKER_REGISTRY-}commandapi
    build:
      context: .
      dockerfile: Services/Command/Command/Dockerfile
  
  aktuator.service:
    image: ${DOCKER_REGISTRY-}aktuatorapi
    build:
      context: .
      dockerfile: Services/Aktuator/Aktuator/Dockerfile

  apigateway:
    image: ${DOCKER_REGISTRY-}apigateway
    build:
      context: .
      dockerfile: Services/APIGateway/APIGateway/Dockerfile

